{
 "title": "Demo dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Operation Duration",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(operation_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Operation Exception",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(operations_failed_invalid_operation_exception_total[$__rate_interval]))",
     "legendFormat": "Exception Count"
    }
   ]
  },
  {
   "title": "Operations In Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "targets": [
    { "expr": "operations_in_progress", "legendFormat": "Count" }
   ]
  }
 ]
}