version: '3.4'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

  grafana:
    build: "./grafana"
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana:/var/lib/grafana
  api:
    image: ${DOCKER_REGISTRY-}api
    restart: always
    ports:
      - "8181:8080"
    build:
      context: .
      dockerfile: Api/Dockerfile
      
volumes:
  prometheus:
    driver: local
  grafana:
    driver: local

